### ISSUE TITLE
[Nominations Open] Best Sigstore Evangelist Award 2022 🏆

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/community#124]
This issue is to receive nominations for the Best Sigstore Evangelist Award 2022.

This award recognizes a champion for Sigstore projects. This individual helps spread awareness of Sigstore and its projects. They bring Sigstore to new communities, driving interest and excitement around the ecosystem. 

To nominate someone, reply to this issue with the following:

Full name of the person you’re nominating
Short description of their contributions to Sigstore and why they should win.
Nomination Deadline: Tuesday, September 20, 2022

More details are available here: https://github.com/sigstore/community/tree/main/awards

**Comment by naveensrinivasan** [comment]
I am nominating @developer-guy 

@developer-guy  has contributed lots of tweets, blogpost , videos on Sigstore related projects!

**Comment by cpanato** [comment]
Also, nominate @developer-guy. He is doing tremendous work spreading the sigstore knowledge around!

**Comment by Saim-Safdar** [comment]
+1 for @developer-guy. He is doing amazing work spreading the knowledge around Sigstore, (blog posts, Tweets, meetups) all are really helpful and the great learning resource for everyone.

**Comment by asraa** [comment]
I NOMINATE @developer-guy 
WE ALL NOMINATE @developer-guy 
![a15127f0ddb9230309bb0b8802b1554e](https://user-images.githubusercontent.com/5194569/190729620-8a374181-b719-47ce-9499-9ac459841207.jpg)

**Comment by hectorj2f** [comment]
I also nominate @developer-guy 👏🏻
