### ISSUE TITLE
"Add team for timestamp codeowners" GHA job failure: 422 Validation Failed 

### ISSUE THREAD

**Issue by tstromberg** [sigstore/community#147]
As mentioned by @priyawadhwa at the sigstore oncall meeting:

https://github.com/sigstore/community/actions/runs/3175965606

```
[Update](https://github.com/sigstore/community/actions/runs/3175965606/jobs/5174727890#step:11:151)
code: 255
 stdout: Updating (sigstore/github-prod)

View Live: https://app.pulumi.com/sigstore/sigstore-github-sync/github-prod/updates/225

@ Updating.....
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:github-prod::sigstore-github-sync::pulumi:pulumi:Stack::sigstore-github-sync-github-prod]
    ~ github:index/teamRepository:TeamRepository: (update)
        [id=6693572:helm-charts]
        [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/teamRepository:TeamRepository::helm-charts-sigstore-oncall]
      ~ permission: "push" => "write"
        repository: "helm-charts"
        teamId    : "6693572"
Resources:
    309 unchanged

Duration: 57s

 stderr: error: 1 error occurred:
	* updating urn:pulumi:github-prod::sigstore-github-sync::github:index/teamRepository:TeamRepository::helm-charts-sigstore-oncall: PUT https://api.github.com/organizations/71096353/team/6693572/repos/sigstore/helm-charts: 422 Validation Failed []


error: update failed

 err?:
```

**Comment by tstromberg** [comment]
Analyzing this with the previous failure, you can see that "pulumi up on sigstore/github-prod" fails on both at the same stage, which is trying to upgrade the sigstore-oncall permission from "push" to "write" for the "helm-charts" repository:

```
 ~ github:index/teamRepository:TeamRepository: (update)
          [id=6693572:helm-charts]
          [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/teamRepository:TeamRepository::helm-charts-sigstore-oncall]
        ~ permission: "push" => "write"
          repository: "helm-charts"
          teamId    : "6693572"
```

**Comment by tstromberg** [comment]
-Doing some cursory research, my first thought experiment would be to manually remove the oncall group from membership to the `helm-charts` GitHub repository, and re-run the script to see if the script works or outputs differently in a way that could help us determine what it's stuck on.

@priyawadhwa - would it be possible to do this?

The only other theory I have is that Github may be complaining that the Team ID and/or Team name do not match it's expectation (hence 422 "Validation Failed")

**Comment by tstromberg** [comment]
Here's the API reference: https://docs.github.com/en/rest/teams/teams#add-or-update-team-repository-permissions - it does not mention the 422 status code.

**Comment by priyawadhwa** [comment]
I think Carlos might have fixed this with https://github.com/sigstore/community/pull/145!

**Comment by priyawadhwa** [comment]
Yep looks like the most recent run was green (https://github.com/sigstore/community/actions/runs/3177181864) , I think we're good. Going ahead and closing this issue :)
