### ISSUE TITLE
Defining status checks in the repository

### ISSUE THREAD

**Issue by asraa** [sigstore/community#187]
I have a quick request, and have no idea if this is possible with Pulumi.

Adding new CI workflows, or changing the required status checks, currently requires maintainers to make a PR in sigstore/community. Is it possible for the stub of the config on status checks to live in the individual repositories? 

Once branch protection is set in this one, then it should be safe for the individual repositories to commit the configuration for status checks in their own repositories. 

@cpanato maybe you might know?

**Comment by haydentherapper** [comment]
I don't think you can configure status checks as a maintainer though since it's branch protection, you'd need to be an admin.

**Comment by cpanato** [comment]
ok, I will work to remove the status check from the automation and leave to the maintainers to select in the UI which ones they want

**Comment by cpanato** [comment]
we reverted due some issues and to not give admin permissions to all the maintainers, for now we will keep using the automation to set the status check and other branch protection settings

cc @haydentherapper @bobcallaway 

will close this for now
