### ISSUE TITLE
Post Terms of Use for Public Sigstore Infrastructure

### ISSUE THREAD

**Issue by steiza** [sigstore/community#192]
I believe the Linux Foundation has drafted some suggested language for Terms of Use for the public Sigstore infrastructure.

Once the drafted has been reviewed and posted at a public URL, we can link to it as we work on things like [npm supports creating verifiable links between a package version and its source/build - Public beta](https://github.com/github/roadmap/issues/612).

**Comment by haydentherapper** [comment]
cc @bobcallaway

**Comment by haydentherapper** [comment]
This has been completed.
