### ISSUE TITLE
Index of Sigstore case studies

### ISSUE THREAD

**Issue by joshuagl** [sigstore/community#207]
I was looking for the Sigstore case-studies and couldn't easily find them indexed in one place. I was able to find them by searching on Medium, but perhaps we can list them somewhere (in the community repo? on sigstore.dev?) with a brief summary to help potential readers find them?

Case-studies I found:
* DB Schenker: internal supply chain integrity https://blog.sigstore.dev/securing-your-software-supply-chain-without-changing-your-devops-workflow-e23393a5fffa
* Verizon: attaining SLSA level 3 https://blog.sigstore.dev/security-by-default-how-verizon-new-business-incubation-uses-sigstore-to-demonstrate-provenance-7beed5714738
* Autodesk: meeting FedRAMP compliance requirements https://blog.sigstore.dev/using-sigstore-to-meet-fedramp-compliance-at-autodesk-6f645a920abc

**Comment by joshuagl** [comment]
cc @tracymiranda

**Comment by bobcallaway** [comment]
Are you thinking of https://github.com/sigstore/friends ?

**Comment by joshuagl** [comment]
I just found that the case studies are listed on the [Sigstore landscape](https://landscape.openssf.org/sigstore) (and that there are five, not the three I originally found through searching).

**Comment by znewman01** [comment]
CC @tracymiranda ICYMI

**Comment by tracymiranda** [comment]
Thanks @znewman01 

Yes, @joshuagl the landscape is intended to be the source of truth for the case studies. The nice thing about it is that you can link out the groups and embed them elsewhere... so for example we could embed this link somewhere on the website or wherever makes sense for discoverability

https://landscape.openssf.org/card-mode?category=case-studies&grouping=category&embed=yes&style=borderless
