### ISSUE TITLE
Trim cosign-codeowners list

### ISSUE THREAD

**Issue by znewman01** [sigstore/community#208]
**Action required** if your name is below and you'd like to keep access to Cosign.

Hey all,

We've managed to accumulate quite a few cosign-codeowners:

- @Dentrax 
- @asraa 
- @bobcallaway 
- @dekkagaijin
- @developer-guy 
- @dlorenc 
- @font 
- @hectorj2f 
- @loosebazooka 
- @luhring 
- @lukehinds 
- @mattmoor 
- @n3wscott 
- @priyawadhwa 
- @vaikas 
- @znewman01 

This makes it hard to make changes that we'd want every owner's consent for (for example, https://github.com/sigstore/cosign/pull/2519 ).

Let's tidy up. I'm going to remove anybody who no longer can prioritize maintaining Cosign. If you'd like to stay on as a Cosign codeowner, please 👍 this comment by this time next week, Monday Jan 16th. (If you happen to miss it after we clean up I'm happy to add you back.)

**Comment by loosebazooka** [comment]
![image](https://user-images.githubusercontent.com/1304826/211399427-606848f6-db66-4a3e-9b1a-dc99a03eae1c.png)

**Comment by haydentherapper** [comment]
Should this be based on whether the maintainer is adhering to the community guidelines? For example, if there has been no recent development or reviews, probably should remove the maintainer.

**Comment by dlorenc** [comment]
> Should this be based on whether the maintainer is adhering to the [community guidelines](https://github.com/sigstore/community/blob/main/MEMBERSHIP.md#responsibilities-and-privileges-2)? For example, if there has been no recent development or reviews, probably should remove the maintainer.
> Edit: There are guidelines for [inactive members](https://github.com/sigstore/community/blob/main/MEMBERSHIP.md#inactive-members) too.

It's best to apply some judgement on stuff like this but definitely base it on the guidelines. I've seen projects trim too aggressively to the point where they don't even have enough people to keep it running and add more people back.

**Comment by vaikas** [comment]
Not directly related to this PR but got me thinking :) 

I just wanted to throw out some learnings that we had in Knative wrt achieving consensus, so just wanted to share that here as something to think about moving forward. Here's the process as well as some background that we found quite useful.

I think reducing the number of owners is fine, but I'm not quite sure it addresses the fundamental problem of getting the consensus. I'm not sure we need this, but just figured it might be useful to think about :) 

https://docs.google.com/document/d/1l7pWR2qyEgmCu1zbYwiufQH6aSM9DnwlJ1xtjuxz4MA/edit#heading=h.rlgskeckhfva

More background / discussions here:
https://github.com/sigstore/cosign/issues/2466

**Comment by cpanato** [comment]
fun fact, i'm not part of the cosign lol
