### ISSUE TITLE
Logo for Sigstore's `policy-controller` component/project

### ISSUE THREAD

**Issue by mathieu-benoit** [sigstore/community#220]
It would be great to have a dedicated logo for the Sigstore's `policy-controller` component/project, is it planned?

It was/is not part of:
- https://blog.sigstore.dev/new-sigstore-landscape-add-your-signed-project-dda0517723b6
- https://github.com/sigstore/community/tree/main/artwork

And then it's maybe the opportunity to add it in there https://landscape.openssf.org/sigstore too?

**Comment by tracymiranda** [comment]
cc @cpanato @vaikas @hectorj2f 
I can help kick off a request for this - what we need first is some input for the designer aka a creative brief. 
Here is the doc we used for Sigstore - https://docs.google.com/document/d/1VBauFzVIRv9Ert-CWElbVzZywsRvS1ZjDFHDTW-AHUA/edit#heading=h.uh4tgxrtvxpy 

The main thing we need is the design considerations e.g do we want it to be very close to sigstore logo or unique but related (e.g. rekor).

**Comment by hectorj2f** [comment]
Yeah, i agree with @cpanato here. We should remain simple and follow sigstore log with a symbol remaining rules/policies.

**Comment by vaikas** [comment]
Maybe something simple like 'shield'? 🤔

**Comment by hectorj2f** [comment]
If I have to choose then a `shield`.

**Comment by amdawson** [comment]
the cosign pen icon inside a shield might be good. 

dumb mockup attached
![md_5b29c1da3aad6](https://user-images.githubusercontent.com/8444505/224343961-f14de412-6df2-466e-b624-ecdff9dc5207.jpg)

**Comment by cpanato** [comment]
looks nice

**Comment by mathieu-benoit** [comment]
love it too!

**Comment by mathieu-benoit** [comment]
Actually, it seems that it will be the only one not being a stamp like the other ones, right?

https://blog.sigstore.dev/new-sigstore-landscape-add-your-signed-project-dda0517723b6/

So, what about having the stamp and the shield in white inside it? Same approach than the other ones.

**Comment by elfotografo007** [comment]
I believe there is some kind of copyright issue with the stamp/wax seal but I agree that this logo should be consistent with the other new logos.

**Comment by hectorj2f** [comment]
Yes, I agree with @vaikas and @mathieu-benoit, as long as it is inside a stamp :).

**Comment by sheesh** [comment]
Just to confirm, folks here are interested in a logo that uses a dark blue wax stamp with a white shield logo inside? And the dark blue is a _new_ color, not the same color as the Sigstore logo? 

@elfotografo007 are there copyright issues I should note? 

Thanks!

**Comment by tracymiranda** [comment]
yes think referring to this https://github.com/sigstore/community/issues/239

**Comment by sheesh** [comment]
Thanks! Will make a note of it in the Creative Brief.

**Comment by sheesh** [comment]
The designer should have a draft logo next Thursday, 3/23. I'll follow up then for community feedback.

**Comment by tracymiranda** [comment]
Thanks @sheesh for helping accelerate this!

**Comment by sheesh** [comment]
Hi all! The designer came back with four different concepts for the policy-controller logo. Let me know your preference and if you have any other feedback. Thanks! 

[Sigstore_PolicyController_Concepts_v1.pdf](https://github.com/sigstore/community/files/11055239/Sigstore_PolicyController_Concepts_v1.pdf)

**Comment by elfotografo007** [comment]
My favorites are concept 2 and 1 (in that order)

**Comment by vaikas** [comment]
Looks fantastic, thank you so much for getting these done!!!

I like them in order of preference:
3
4
1
2

**Comment by jkjell** [comment]
So cool!  I like 1 & 2.  I would be a little concerned about 4's shield looking like the Windows Defender [logo](https://techdator.net/wp-content/uploads/2020/08/Windows-defender.jpg).

**Comment by derwei** [comment]
Those are awesome! Love how simple and elegant they are! 
I like 1, 2, 4, 3 (in order) - I cant unsee the windows defender logo from #3 now

**Comment by mathieu-benoit** [comment]
Awesome! My vote in order goes: 1, 4, 3, 2.

**Comment by hectorj2f** [comment]
They all look really good. I vote for 2, 1 and 3 in that order.

**Comment by cpanato** [comment]
in order: 3, 1, 2, 4

**Comment by sheesh** [comment]
Concept 1 is in the lead! But @amdawson and @tracymiranda could still swing the vote! 

Is there anyone besides the 10 participants here that should weigh in?

**Comment by sheesh** [comment]
Thanks, @amdawson! And good flag about layout--I'll let the designer know.

**Comment by imjasonh** [comment]
1, 2, 3, 4 for me.

4 has religious connotations to me, like a Knights Templar shield.

**Comment by pwelch** [comment]
1, 3, 2, 4

**Comment by mattmoor** [comment]
2, 1, 3, 4

Excited for this!

**Comment by codysoyland** [comment]
1, 2, 3, 4... Really loving the branding!

**Comment by nickvidal** [comment]
That would be 1, 2, 4, 3 for me. Thanks!

**Comment by sheesh** [comment]
hey @haydentherapper - good flag about the length of the project name. i'm not sure what can be done on this front at this moment (since renaming is out of scope), but i'll see if the designer has any ideas. thanks!

**Comment by sheesh** [comment]
Thanks everyone for your votes and feedback. Concept 1 is the clear winner! 

I will send on our choice to the designer and ask if she has ideas for minimizing the length of the name.  I can also let her know that if she provides an image of all the logos together, this logo should be at the bottom.

**Comment by sheesh** [comment]
Happy Friday, everyone! 

The designer sent some [variations on Concept 1](https://github.com/sigstore/community/files/11123437/Sigstore_PolicyController_Concepts_v2.pdf) that help minimize the width of the `policy-controller` logo. (Thanks, @haydentherapper, for the flag). Personally, I think Concept 1D might work the best but I'm interested in the group's thoughts. 

Let me know if you have opinions. I'd like to send her our final decision by end of day Monday. Thanks!

**Comment by ltagliaferri** [comment]
Seconding Concept 1D, thank you for your work on this @sheesh !

**Comment by hectorj2f** [comment]
Yes, 1D also looks good to me. Thanks everyone.

**Comment by sheesh** [comment]
Great! I will write the designer that we prefer 1D unless I hear strong opinions otherwise before the end of the day. Thanks!

**Comment by mathieu-benoit** [comment]
+1 for 1D, thanks @sheesh!

**Comment by cpanato** [comment]
1d as well

**Comment by hectorj2f** [comment]
@sheesh I'd say you can store them here: https://github.com/sigstore/community/tree/main/artwork

**Comment by sheesh** [comment]
Thank you, @hectorj2f!

**Comment by sheesh** [comment]
Hooray, new logos are added in this PR: https://github.com/sigstore/community/pull/257

**Comment by sheesh** [comment]
Hey there! Just checking in to see if there is anything I need to do to get the logo PR merged? Tips appreciated! :) 

#257

**Comment by tracymiranda** [comment]
I'll ask in slack if we can get a reviewer with merge rights to look at this...
