### ISSUE TITLE
Maintainer/triage permissions for @tnytown

### ISSUE THREAD

**Issue by woodruffw** [sigstore/community#240]
Hello!

This is a request to have my colleague @tnytown added to a few Sigstore repos. The "triage" permission should be sufficient, but "maintain" would also be fine. 

The repos in question:

* `sigstore-python`
* `gh-action-sigstore-python`
* `sigstore-conformance`

**Comment by tnytown** [comment]
Hey! Confirming that I'm aware of this request and I'd like these perms :)

**Comment by bobcallaway** [comment]
can you create a PR to add @tnytown to the files in https://github.com/sigstore/community/tree/main/github-sync with triage? `maintain` should ideally follow our [published contributor ladder](https://github.com/sigstore/community/blob/main/MEMBERSHIP.md)

**Comment by woodruffw** [comment]
Will do! Thanks.

**Comment by woodruffw** [comment]
#241.

**Comment by haydentherapper** [comment]
@bobcallaway @priyawadhwa We can close this as completed
