### ISSUE TITLE
update calendar invite for the weekly call link

### ISSUE THREAD

**Issue by Neilblaze** [sigstore/community#261]
### Description

The personalized direct invite [link](https://calendar.google.com/event?action=TEMPLATE&tmeid=Njc2b2xoYTlkamdlaGN1MTMza3ZoM21iZXZfMjAyMTAzMTZUMTczMDAwWiBkbWk5M3Nibjl0OTJqZTlobXVodXVsYnZma0Bn&tmsrc=dmi93sbn9t92je9hmuhuulbvfk%40group.calendar.google.com&scp=ALL) for Community Meetings displays previously happened events (Mar 2021). Feel free to head over to [this](https://github.com/sigstore/community#community-meetings:~:text=We%20also%20used%20to%20use%20a%20specific%20calendar%20invite%20for%20the%20weekly%20call.%20This%20direct%20link%20will%20continue%20to%20work%20as%20well%2C%20and%20is%20available%20here) to explore.

![image](https://user-images.githubusercontent.com/48355572/233807753-da3e35c9-0031-418e-8788-25350335d17e.png)

### Solution 

The gCal link should be updated with a new one.

/cc: @priyawadhwa, @ltagliaferri

**Comment by priyawadhwa** [comment]
I can't find a way to get a link to all events -- maybe it would be better to replace the link with the hangouts meeting code?

**Comment by ltagliaferri** [comment]
@tracymiranda — since you own the meeting maybe you can make a call about how to move forward with this
