### ISSUE TITLE
add pulumi automation for newly-created sigstore-conformance org

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/community#264]
Per discussion in https://github.com/sigstore/sigstore-conformance/pull/71, we agreed to create a separate GH organization to generate tokens for testing against the conformance suite. 

There are currently two repos under this new org (https://github.com/sigstore-conformance/.github and https://github.com/sigstore-conformance/extremely-dangerous-public-oidc-beacon). I added the current TAC users as org admins, and have @woodruffw and @tetsuo-cpp as maintainers on these two projects - however it would be ideal if we could add this new org into our pulumi-based GH-config-as-code system.

@cpanato any chance you could help with this?

**Comment by cpanato** [comment]
yes, will work on that
