### ISSUE TITLE
Community Chair Election

### ISSUE THREAD

**Issue by lukehinds** [sigstore/community#276]
The community chair position is now open for nominees. 

Contributors (commits or issues raised / past attendance to the community meetings) who are active in sigstore can self nominate. 

Please drop you name below, with a quick bio and why you think you would be suited for the role.

Duties include:

* Pre-set the agenda before the meeting
* Record the meeting
* Work through the agenda during the meeting, while making sure either yourself or someone else takes minutes.
* Timebox discussions if needed and consider if they could use a break out or revisiting at the next meeting.

This week will be used to gather nominees with a freeze on 06/04/23 Midnight EST. 

if there is only a single nomination, they will become the new chair, if more, I will set up a vote to take place on the 06/02/23 (details to follow).

The new chairs first meeting will be on the 06/13/23

**Comment by haydentherapper** [comment]
Hey everyone, I would like to nominate myself to be the community chair. My current role is a technical lead and manager at Google, working on open source supply chain security. I’ve been a part of the Sigstore community for over a year, serving as a maintainer of multiple repositories and participating in oncall for the infrastructure. I’ve been a guest community chair on several occasions and would be thrilled to serve as the community chair for this cycle.

**Comment by haydentherapper** [comment]
Thank you @tracymiranda for all of the amazing work you've done with the Sigstore community!
