### ISSUE TITLE
Create sigstore-bot GitHub account

### ISSUE THREAD

**Issue by cpanato** [sigstore/community#29]
- To perform any automation/tasks that we as humans will not do with our own account

/assign @cpanato

**Comment by cpanato** [comment]
cc @lukehinds

**Comment by letmaik** [comment]
Just out of curiosity, which use cases don't work with `GITHUB_TOKEN`?

**Comment by cpanato** [comment]
@letmaik I was checking some milestone applier for PR and we need to add the secret for that, but I will double-check.
But maybe in the future, we have more things that need a bot to perform actions that we don't want to attach to a specific user.

**Comment by lukehinds** [comment]
I totally missed this first time around, is this still applicable @cpanato ?

**Comment by cpanato** [comment]
me too, forgot this issue, we can close, we already have the bot account :)
