### ISSUE TITLE
Create /research/ folder and add projectsbyIF insights deck

### ISSUE THREAD

**Issue by peterkwells** [sigstore/community#33]
Over time the sigstore community will create research. An example is the current projectsbyIF work. This research may be useful for the current and future sigstore communities.

Creating a /community/research/ folder will provide a simple, initial mechanism for storing and providing access to research.

A first entry could be the projectsbyIF research insights document:

[[external] sigstore discovery – research insights.pdf](https://github.com/sigstore/community/files/6553415/external.sigstore.discovery.research.insights.pdf)

(To reduce effort for others I would connect this issue to a PR with proposed changes but don't have the github rights :))

**Comment by dlorenc** [comment]
Thanks! We'll get this merged.
