### ISSUE TITLE
pulumi run partially failed for new repository (root-signing-staging) 

### ISSUE THREAD

**Issue by jku** [sigstore/community#354]
This is related to #351 (intention was to create a project and set permissions for teams and bots)
* the project was created -- https://github.com/sigstore/root-signing-staging exists now
* The workflow still failed (https://github.com/sigstore/community/actions/runs/6643534604/job/18050779700). I don't think the permission assignments have happened -- I don't seem to have any in the project
* there are several failures with `error: PATCH https://api.github.com/repos/sigstore/root-signing-staging: 404 Not Found` -- this is strange since that API endpoint clearly does exist
* I'm not familiar enough with pulumi to understand if this failure is in sigstore/github-sync code or somewhere in pulumi?

Log is copy-pasted below for convenience (click to reveal)

<details>
  <summary>pulumi up log</summary>

    pulumi up on sigstore/github-prod
      Updating (sigstore/github-prod)
      
      
      View Live: https://app.pulumi.com/sigstore/sigstore-github-sync/github-prod/updates/591
      
      
      @ Updating....
      .
      .
      
      
        pulumi:pulumi:Stack: (same)
          [urn=urn:pulumi:github-prod::sigstore-github-sync::pulumi:pulumi:Stack::sigstore-github-sync-github-prod]
      
      @ Updating....
      
      
          + github:index/branchDefault:BranchDefault: (create)
              [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/branchDefault:BranchDefault::root-signing-staging]
              branch    : "main"
              rename    : false
              repository: "root-signing-staging"
          + github:index/repository:Repository: (create) 🔒
              [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/repository:Repository::root-signing-staging]
              allowAutoMerge          : false
              allowMergeCommit        : true
              allowRebaseMerge        : false
              allowSquashMerge        : false
              archived                : false
              autoInit                : false
              deleteBranchOnMerge     : false
              description             : "Staging TUF repository for Sigstore trust root"
              hasDiscussions          : false
              hasDownloads            : false
              hasIssues               : true
              hasProjects             : false
              hasWiki                 : false
              homepageUrl             : ""
              isTemplate              : false
              licenseTemplate         : ""
              mergeCommitMessage      : "PR_TITLE"
              mergeCommitTitle        : "MERGE_MESSAGE"
              name                    : "root-signing-staging"
              squashMergeCommitMessage: "COMMIT_MESSAGES"
              squashMergeCommitTitle  : "COMMIT_OR_PR_TITLE"
              topics                  : []
              visibility              : "public"
              vulnerabilityAlerts     : true
      
              --outputs:--
              allowUpdateBranch       : false
              defaultBranch           : "main"
              etag                    : "W/\"aa001b8eca48f1104c601ca71bc98fdfd9ab2bb83ab1fe53afe6d8c1271bae95\""
              fullName                : "sigstore/root-signing-staging"
              gitCloneUrl             : "git://github.com/sigstore/root-signing-staging.git"
              htmlUrl                 : "https://github.com/sigstore/root-signing-staging"
              httpCloneUrl            : "https://github.com/sigstore/root-signing-staging.git"
              id                      : "root-signing-staging"
              nodeId                  : "R_kgDOKlCAEA"
              private                 : false
              repoId                  : 709918736
              securityAndAnalysis     : {
                  advancedSecurity            : <null>
                  secretScanning              : {
                      status: "enabled"
                  }
                  secretScanningPushProtection: {
                      status: "disabled"
                  }
              }
              sshCloneUrl             : "git@github.com:sigstore/root-signing-staging.git"
              svnUrl                  : "https://github.com/sigstore/root-signing-staging"
      
      Resources:
          + 1 created
          441 unchanged
      
      Duration: 1m30s
      
      
      /home/runner/work/_actions/pulumi/actions/1d3ebd326317f2493[137](https://github.com/sigstore/community/actions/runs/6643534604/job/18050779700#step:3:144)06eeb489c9ed7c036443/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77
                          : new CommandError(result);
      ^
      CommandError: code: -2
       stdout: 
       stderr: Command failed with exit code 255: pulumi up --yes --skip-preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --stack sigstore/github-prod --non-interactive
      [resource plugin github-5.21.0] installing
      [resource plugin github-5.20.0] installing
      error: PATCH https://api.github.com/repos/sigstore/root-signing-staging: 404 Not Found []
      error: update failed
      Updating (sigstore/github-prod)
      
      View Live: https://app.pulumi.com/sigstore/sigstore-github-sync/github-prod/updates/591
      
      @ Updating......
        pulumi:pulumi:Stack: (same)
          [urn=urn:pulumi:github-prod::sigstore-github-sync::pulumi:pulumi:Stack::sigstore-github-sync-github-prod]
      @ Updating....
          + github:index/branchDefault:BranchDefault: (create)
              [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/branchDefault:BranchDefault::root-signing-staging]
              branch    : "main"
              rename    : false
              repository: "root-signing-staging"
          + github:index/repository:Repository: (create) 🔒
              [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/repository:Repository::root-signing-staging]
              allowAutoMerge          : false
              allowMergeCommit        : true
              allowRebaseMerge        : false
              allowSquashMerge        : false
              archived                : false
              autoInit                : false
              deleteBranchOnMerge     : false
              description             : "Staging TUF repository for Sigstore trust root"
              hasDiscussions          : false
              hasDownloads            : false
              hasIssues               : true
              hasProjects             : false
              hasWiki                 : false
              homepageUrl             : ""
              isTemplate              : false
              licenseTemplate         : ""
              mergeCommitMessage      : "PR_TITLE"
              mergeCommitTitle        : "MERGE_MESSAGE"
              name                    : "root-signing-staging"
              squashMergeCommitMessage: "COMMIT_MESSAGES"
              squashMergeCommitTitle  : "COMMIT_OR_PR_TITLE"
              topics                  : []
              visibility              : "public"
              vulnerabilityAlerts     : true
              --outputs:--
              allowUpdateBranch       : false
              defaultBranch           : "main"
              etag                    : "W/\"aa001b8eca48f1104c601ca71bc98fdfd9ab2bb83ab1fe53afe6d8c1271bae95\""
              fullName                : "sigstore/root-signing-staging"
              gitCloneUrl             : "git://github.com/sigstore/root-signing-staging.git"
              htmlUrl                 : "https://github.com/sigstore/root-signing-staging"
              httpCloneUrl            : "https://github.com/sigstore/root-signing-staging.git"
              id                      : "root-signing-staging"
              nodeId                  : "R_kgDOKlCAEA"
              private                 : false
              repoId                  : 7099[187](https://github.com/sigstore/community/actions/runs/6643534604/job/18050779700#step:3:194)36
              securityAndAnalysis     : {
                  advancedSecurity            : <null>
                  secretScanning              : {
                      status: "enabled"
                  }
                  secretScanningPushProtection: {
                      status: "disabled"
                  }
              }
              sshCloneUrl             : "git@github.com:sigstore/root-signing-staging.git"
              svnUrl                  : "https://github.com/sigstore/root-signing-staging"
      Resources:
          + 1 created
          441 unchanged
      
      Duration: 1m30s
       err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --stack sigstore/github-prod --non-interactive
      [resource plugin github-5.21.0] installing
      [resource plugin github-5.20.0] installing
      error: PATCH https://api.github.com/repos/sigstore/root-signing-staging: 404 Not Found []
      error: update failed
      Updating (sigstore/github-prod)
      
      View Live: https://app.pulumi.com/sigstore/sigstore-github-sync/github-prod/updates/591
      
      @ Updating......
        pulumi:pulumi:Stack: (same)
          [urn=urn:pulumi:github-prod::sigstore-github-sync::pulumi:pulumi:Stack::sigstore-github-sync-github-prod]
      @ Updating....
          + github:index/branchDefault:BranchDefault: (create)
              [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/branchDefault:BranchDefault::root-signing-staging]
              branch    : "main"
              rename    : false
              repository: "root-signing-staging"
          + github:index/repository:Repository: (create) 🔒
              [urn=urn:pulumi:github-prod::sigstore-github-sync::github:index/repository:Repository::root-signing-staging]
              allowAutoMerge          : false
              allowMergeCommit        : true
              allowRebaseMerge        : false
              allowSquashMerge        : false
              archived                : false
              autoInit                : false
              deleteBranchOnMerge     : false
              description             : "Staging TUF repository for Sigstore trust root"
              hasDiscussions          : false
              hasDownloads            : false
              hasIssues               : true
              hasProjects             : false
              hasWiki                 : false
              homepageUrl             : ""
              isTemplate              : false
              licenseTemplate         : ""
              mergeCommitMessage      : "PR_TITLE"
              mergeCommitTitle        : "MERGE_MESSAGE"
              name                    : "root-signing-staging"
              squashMergeCommitMessage: "COMMIT_MESSAGES"
              squashMergeCommitTitle  : "COMMIT_OR_PR_TITLE"
              topics                  : []
              visibility              : "public"
              vulnerabilityAlerts     : true
              --outputs:--
              allowUpdateBranch       : false
              defaultBranch           : "main"
              etag                    : "W/\"aa001b8eca48f1104c601ca71bc98fdfd9ab2bb83ab1fe53afe6d8c1271bae95\""
              fullName                : "sigstore/root-signing-staging"
              gitCloneUrl             : "git://github.com/sigstore/root-signing-staging.git"
              htmlUrl                 : "https://github.com/sigstore/root-signing-staging"
              httpCloneUrl            : "https://github.com/sigstore/root-signing-staging.git"
              id                      : "root-signing-staging"
              nodeId                  : "R_kgDOKlCAEA"
              private                 : false
              repoId                  : 709918736
              securityAndAnalysis     : {
                  advancedSecurity            : <null>
                  secretScanning              : {
                      status: "enabled"
                  }
                  secretScanningPushProtection: {
                      status: "disabled"
                  }
              }
              sshCloneUrl             : "git@github.com:sigstore/root-signing-staging.git"
              svnUrl                  : "https://github.com/sigstore/root-signing-staging"
      Resources:
          + 1 created
          441 unchanged
      
      Duration: 1m30s
      
          at Object.createCommandError (/home/runner/work/_actions/pulumi/actions/1d3ebd326317f[249](https://github.com/sigstore/community/actions/runs/6643534604/job/18050779700#step:3:256)313706eeb489c9ed7c036443/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77:1)
          at Object.<anonymous> (/home/runner/work/_actions/pulumi/actions/1d3ebd3[263](https://github.com/sigstore/community/actions/runs/6643534604/job/18050779700#step:3:270)17f249[313](https://github.com/sigstore/community/actions/runs/6643534604/job/18050779700#step:3:320)706eeb489c9ed7c036443/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:76:1)
          at Generator.throw (<anonymous>)
          at rejected (/home/runner/work/_actions/pulumi/actions/1d3ebd326[317](https://github.com/sigstore/community/actions/runs/6643534604/job/18050779700#step:3:324)f249313706eeb489c9ed7c036443/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:19:1)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)

</details>

**Comment by cpanato** [comment]
all good now :)
