### ISSUE TITLE
setting GH actions variables in a project?

### ISSUE THREAD

**Issue by jku** [sigstore/community#360]
I'd like to set two GitHub Actions variables in the https://github.com/sigstore/root-signing-staging project.
I don't see a way to do that with the config here but I also don't have permission (as maintainer) to set them in the GitHub UI.

What's the suggested solution to this:
* should I add one of the maintainers separately as a admin-collaborator to the repository, so they can do the change
* or are there org admins that could already set the variables if I ask nicely?

This is not urgent right now as I don't have the variable values yet but https://github.com/sigstore/root-signing-staging/issues/8 has the details

**Comment by haydentherapper** [comment]
I would make yourself an admin, we have the same set up for other projects that require adding secrets.
