### ISSUE TITLE
Microsoft in this space trying to standardize with IETF?

### ISSUE THREAD

**Issue by deeglaze** [sigstore/community#379]
Hi folks, I recently came across a [CACM article from Microsoft folks](https://queue.acm.org/detail.cfm?id=3623460) including the Azure CTO about a Code Transparency Service, which sounds exactly like sigstore. Furthermore, there is a new workstream in IETF called [SCITT](https://datatracker.ietf.org/wg/scitt/about/) that is attempting to define a standard around such transparency services.

Wondering if any of y'all have seen this and are interested in joining that workstream to avoid an unpleasant situation of API divergence in the attestation ecosystem.

**Comment by haydentherapper** [comment]
Cleaning up old issues - Feel free to reopen if there is more discussion to be had.
