### ISSUE TITLE
Pulumi up fails on main

### ISSUE THREAD

**Issue by jku** [sigstore/community#397]
Currently "pulumi up" ([github-sync-main-sigstore](https://github.com/sigstore/community/actions/workflows/github-sync-main-sigstore.yml)) fails consistently on main. See example:
https://github.com/sigstore/community/actions/runs/7703455029/job/20993867318

The failure is 
> 422 Commit signoff is enforced by the organization and cannot be disabled []

* it's currently unclear why this started to suddenly fail between d9bdb66 and a388f3f : the config does not actually try to set webCommitSignoffRequired anywhere...
* Bob tried to fix this by explicitly setting all repositories webCommitSignoffRequired to true in5a77a4b : this did not help

**Comment by jku** [comment]
Based on github-sync commits the differences between last working and first failing runs is
* Bump github.com/pulumi/pulumi-github/sdk/v5 from 5.24.0 to 5.25.0
* Bump github.com/pulumi/pulumi/sdk/v3 from 3.100.0 to 3.101.1

This does not exactly match the linked issue but is likely related.

**Comment by cpanato** [comment]
fixed.
We need to disable the org policy for commit signoff and apply that for the repos we want, as we already did looks like.
I've disable that setting now.
cc @bobcallaway 


![Screenshot 2024-02-07 at 09 40 41](https://github.com/sigstore/community/assets/4115580/9d8676ef-2cd1-42e2-ba43-33a7759b5cb5)

**Comment by haydentherapper** [comment]
Thanks yall for looking into this!
