### ISSUE TITLE
Sigstore community meeting times and time zones are incorrect

### ISSUE THREAD

**Issue by rgreinho** [sigstore/community#41]
## Description

<img width="770" alt="image" src="https://user-images.githubusercontent.com/6969134/143061194-c2dc8d73-a070-45a6-a92d-621550ba96ba.png">

The page shows that the meeting will start at 1030am CST, which is incorrect. The meeting actually starts at 1130am CST. 

Bellow that, it is mentioned that the meeting in the local time is 1130am CDT which is also incorrect incorrect because we are not in CDT anymore. Daylight Saving Time (Central Daylight Time (CDT), UTC -5) ended on Nov 7, 2021 and will restart on  March 13, 2022.

So it looks like the times and time zones got mixed on the page, which is confusing.

**Comment by lukehinds** [comment]
pretty sure this is fixed now
