### ISSUE TITLE
Using Github roadmaps for project tracking

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/community#43]
As a new contributor, I want to be able to easily determine what are the goals of the project, what is the long-term direction of the project, and what is actively being worked on.

To solve the first two, I propose we more heavily utilize the roadmap feature on Github to track goals for cosign, fulcio and rekor. We should also schedule periodic triaging of open tickets.

Context: [New contributor friction log](https://docs.google.com/document/d/1HagEnvYF-aHvRt0oh6_YLdCvic9pmU2KfzO7TUek4_4/edit?resourcekey=0-HngMnlcaCXZnR5MU5oqSXw)

**Comment by lukehinds** [comment]
I would be supportive of using github milestones for release planning. Are there any communities around that have a decent process we could replicate?

**Comment by dlorenc** [comment]
The new github projects tool is still in beta but it's much much much better than the old one. It's still missing a few pieces around automation to really make it work. This is a struggle for every project I've seen.

**Comment by haydentherapper** [comment]
Nothing to do at the org level, closing this out
