### ISSUE TITLE
sync-changes failing at HEAD

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/community#442]
https://github.com/sigstore/community/actions/runs/8905874264/job/24457154923

cc @jku might be related to the pulumi update

**Comment by jku** [comment]
It's a bit of a mystery and pulumi isn't making the debugging easy...  It seems to imply that we have already created a branch protection rule for this repo:branch combination but we don't seem to be doing that.

The only real search hit with the term is this  https://github.com/integrations/terraform-provider-github/issues/1699 but I don't quite understand the concept there...

**Comment by cpanato** [comment]
fixed, seems all good now
