### ISSUE TITLE
Outline process for maintainer promotion

### ISSUE THREAD

**Issue by lukehinds** [sigstore/community#52]
Document what is the expected duties of a maintainer and how a maintainer is nominated and on boarded (and off boarded). Some considerations:

* Can someone self nominate, or should an existing maintainer nominate the individual
* Should there be an outline of what makes a good maintainer (contributions (perhaps a key feature), thoughtful reviews etc). I don't think we can set a criteria and enforce it, but we can at least give contributors some insight into some level of expectation we have.
* Should there be some expectations of what a maintainer should do (chop the wood / carry water , so triage issues / house keep the project).

**Comment by dlorenc** [comment]
IMO:


> * Can someone self nominate, or should an existing maintainer nominate the individual

I think anyone should be able to do the nomination, either a maintainer or the person.

> * Should there be an outline of what makes a good maintainer (contributions (perhaps a key feature), thoughtful reviews etc). I don't think we can set a criteria and enforce it, but we can at least give contributors some insight into some level of expectation we have.

Yeah, we can give some examples. It could be lots of core feature work, or just lots of reviews/maintenance, or something in between. 

> * Should there be some expectations of what a maintainer should do (chop the wood / carry water , so triage issues / house keep the project).

I think there should be a basic handbook. It should include stuff like always acting in the best interest of the project, what to do in case of a conflict between maintainers, etc.
