### ISSUE TITLE
Logo Refesh

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/community#55]
This issue tracks a request to Linux Foundation creative team for a refresh of the logos for Sigstore 

(https://sigstore.slack.com/archives/C01D0PA9QKF/p1644000736824899)

**Comment by tracymiranda** [comment]
Deadline for drafts is this Friday and will be shared here as soon as available!

**Comment by haydentherapper** [comment]
Are there plans to refresh the logos for the components of Sigstore?

**Comment by tracymiranda** [comment]
Yes - once we have a direction for the main logo we will look for complementary logos for the components.

**Comment by hectorj2f** [comment]
I vote for design number 6 🥇

**Comment by dekkagaijin** [comment]
I like the wax seal, would be cool to see riffs on concept 5 (page 6)

**Comment by csantanapr** [comment]
+1 Concept 4

**Comment by dirien** [comment]
+1 concept 18

**Comment by endorama** [comment]
> [Sigstore-logo-presentation-v1.pdf](https://github.com/sigstore/community/files/8420424/Sigstore-logo-presentation-v1.pdf)

I really like the concept of the wax seal! I really like concept 5, but would like to see it in in blue (like concept 1A/B), and 1A (I tend to prefer all lowercase though).

**Comment by cpanato** [comment]
+1 Sigstore - Logo Concept 5

**Comment by simi** [comment]
+1 Sigstore - Logo Concept 5  (:heart: seal, :heart: downcase, :heart: "monospace" font)

**Comment by samj1912** [comment]
+1 concept 5

**Comment by bobcallaway** [comment]
+1 Sigstore - Logo Concept 5

**Comment by jchestershopify** [comment]
+1 to logo concept 5

**Comment by ahrkrak** [comment]
+1 on concept 5

**Comment by tracymiranda** [comment]
Thanks everybody who has shared feedback. Collecting the feedback from this issue, slack, the meeting and twitter the summary is:
1A/1B - 35% liked these. One concern is from a design point is 3 colours means there is no true b&w logo
2 - no significant votes. Some folks liked the seal but overall design was not representative 
3 - no significant votes. Looks too much like an eye or spirograph
4 - 10% liked this version. Most said too similar to other logos such as grafeas or robinhood
5 - 55% liked this version. The seal is cool, format will work well for subcomponents. Also lowercase, monospace preferred. Folks have asked to see it in different colours such as blue from logo #1. 

Thanks all for providing your feedback. 
With that in mind we'll pass this onto the designers and share the next iteration when it's ready. Stay tuned!

**Comment by dirien** [comment]
Thanks @tracymiranda, for the feedback. 

The argument for true b&w makes sense, so I change my vote from 1B to concept 5 😄

**Comment by tracymiranda** [comment]
New round of logos came through 🎉. //cc @bobcallaway @lukehinds @dlorenc 
Please share your feedback!
[Sigstore-logo-presentation-v2.pdf](https://github.com/sigstore/community/files/8481109/Sigstore-logo-presentation-v2.pdf)

**Comment by cpanato** [comment]
+1 on number 1

**Comment by dlorenc** [comment]
Number 1 is so good!

**Comment by hectorj2f** [comment]
Number 1 is my favourite too.

**Comment by samj1912** [comment]
+1 on 1 or 4

**Comment by jchestershopify** [comment]
I like number 1, but there seems to be a mismatch between the big version and the side versions on slide 1.

**Comment by mattmoor** [comment]
I like the wax seal, but 1/3 look a bit like dripping blood, which is a bit off-putting.  Maybe just me.  For the shape, I think #2 is my favorite.

I think I prefer the color scheme of 1 the most, and the orientation of the logo in the seal.

**Comment by haydentherapper** [comment]
+1 to Matt's comment about the dripping. Personally I'm a fan of Number 6's color scheme, 2 and 6 are very similar to me besides the color scheme.

**Comment by fishseabowl** [comment]
+1 on number 4

**Comment by lukehinds** [comment]
Number 4 for me, I don't like the dripping / ye oldy world style of the others.

**Comment by tracymiranda** [comment]
To summarize the feedback:
- there is a strong preference for concept 1 in particular the orientation of symbols, colour and lower case letter. However the stamp part should avoid looking like dripping blood or wet paint so ideally more like the shape in concept
- not quite as many folks, but the runner up logo was concept 4

Overall the key difference between concept 1 and concept 4 is "wax seal" vs "certificate style" logo.
I am going to suggest we lean into the concept 1 'wax seal' for a couple of reasons:
- Wired magazine used the 'wax seal' analogy to talk about Sigstore in this article: https://www.wired.com/story/sigstore-open-source-supply-chain-code-signing/ - storytelling in tech is an important way to communicate and feel this would help convey the importance (even gravitas) of sigstore as the 'wax seal of the digital era' 
- the certificate style logos tend to be used to denote certifications both in academic circles but also 'certified' in the sense of standards (e.g. this sort of thing https://www.vectorstock.com/royalty-free-vector/iso-14001-certified-badge-icon-certification-vector-34533024) plus also some similarities with logos such as cert manager https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png

Please let me know your thoughts!

**Comment by jorydotcom** [comment]
Next Revision - Please share your thoughts here, or in Slack!!
[Sigstore-logo-presentation-v3.pdf](https://github.com/sigstore/community/files/8573589/Sigstore-logo-presentation-v3.pdf)

**Comment by dirien** [comment]
This:
![image](https://user-images.githubusercontent.com/38325136/165690226-baf95a34-9219-43f4-ada0-9e358f90cdeb.png)

**Comment by lukehinds** [comment]
> This: ![image](https://user-images.githubusercontent.com/38325136/165690226-baf95a34-9219-43f4-ada0-9e358f90cdeb.png)

+1 to the above

**Comment by lukehinds** [comment]
> Next Revision - Please share your thoughts here, or in Slack!! [Sigstore-logo-presentation-v3.pdf](https://github.com/sigstore/community/files/8573589/Sigstore-logo-presentation-v3.pdf)

**Comment by cpanato** [comment]
+1 on the above 🎉

**Comment by elfotografo007** [comment]
+1 too

**Comment by mattmoor** [comment]
+1

**Comment by fishseabowl** [comment]
+1 

> > This: ![image](https://user-images.githubusercontent.com/38325136/165690226-baf95a34-9219-43f4-ada0-9e358f90cdeb.png)
> 
> +1 to the above

+1 too

**Comment by chicoVegans** [comment]
> This: ![image](https://user-images.githubusercontent.com/38325136/165690226-baf95a34-9219-43f4-ada0-9e358f90cdeb.png)

+1 too

**Comment by simi** [comment]
+1

**Comment by tracymiranda** [comment]
Thanks for the input everyone, looks like we have a clear favourite. I'll request the full set of design files (colour/B&w, multiple orientations)

**Comment by tracymiranda** [comment]
New logo files have been received, they can be found either at ossf https://github.com/ossf/artwork/tree/master/sigstore or in sigstore repo (after PR is merged) https://github.com/sigstore/community/tree/main/artwork
