### ISSUE TITLE
04/2022 Community Chair

### ISSUE THREAD

**Issue by lukehinds** [sigstore/community#57]
The community chair position is now open for nominees. Contributors (commits or issues raised / past attendance to the community meetings) who are active in sigstore can self nominate. please drop you name below, with a quick bio and why you think you would be suited for the role.

**Comment by dlorenc** [comment]
When should we close this? I'd suggest we keep it open until at least Friday May 6th.

**Comment by lukehinds** [comment]
> When should we close this? I'd suggest we keep it open until at least Friday May 6th.

End of week is what I had in mind. I want to announce it to the community meeting and then let the week play out for nominations.

**Comment by lukehinds** [comment]
Congrats @tracymiranda for being the new community chair !
