### ISSUE TITLE
client reference / standard

### ISSUE THREAD

**Issue by lukehinds** [sigstore/community#58]
Branching off from the sharding discussion https://github.com/sigstore/rekor/issues/806 , we considered that clients could perhaps benefit from a retry handler in event of system outage. There was proposal made that we could benefit from a general client guideline / standard. This would not be concerned with the specifics of the client itself, more on how clients would best be suited to interact with sigstore services (rekor, odic, fulcio).

**Comment by haydentherapper** [comment]
This is being tracked now as part of https://github.com/sigstore/architecture-docs
