### ISSUE TITLE
Move community & tac calendar / agenda docs to community group

### ISSUE THREAD

**Issue by lukehinds** [sigstore/community#6]
@dlorenc , I might need you to do this or you see if you can raise my priv to administrator

https://support.google.com/a/answer/1626902?hl=en

![image](https://user-images.githubusercontent.com/7058938/111065216-85460080-84b0-11eb-84c7-d5acada2d69e.png)

I was just thinking, is there anyone at tektoncd we could chat to and get some invite into how they have things set up?

**Comment by lukehinds** [comment]
if you do up me to admin, use lukehinds@gmail.com, as my RH email is under the RH org which limits what I can do around calendars etc.

**Comment by dlorenc** [comment]
What do you need admin privileges on? I don't think there is a meeting invite anywhere yet.

**Comment by lukehinds** [comment]
I sort of how something set up now, but I am sure it could be improved.

It would be really nice if we could add the sigstore.dev domain to the google group, that way we can have a security@sigstore.dev for anyone wanting to report, also aliases such as welfare@sigstore.dev for anyone with concerns in the community relating to our code of conduct.

**Comment by lukehinds** [comment]
done!
