### ISSUE TITLE
Logo Refresh Stage 2

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/community#61]
Following on from the logo refresh work done in #55 this issue tracks the follow up work, which is:
- update the brand guidelines to match the new logo (https://github.com/sigstore/community/blob/main/artwork/Sigstore_Guidelines_2021.pdf)
- update the subproject logos to be more in keeping with the new logo

**Comment by tracymiranda** [comment]
First drop of palette and subproject designs: 
[Sigstore_ColourPalette_V1.pdf](https://github.com/sigstore/community/files/8900689/Sigstore_ColourPalette_V1.pdf)
[Sigstore_Subprojects_V1.pdf](https://github.com/sigstore/community/files/8900690/Sigstore_Subprojects_V1.pdf)

Please let us know any feedback!

**Comment by haydentherapper** [comment]
Could we try a different set of logos for all of the subprojects? I'd be curious to see some other options. 

Fulcio: An arrow is unrelated to a certificate authority
Rekor: Could we try a few different options? I imagine there are a number of ways we can represent a log.
Cosign: I like this one, though I'd also be interested to see some alternatives.

As discussed at the community meeting, it would also be good for Rekor and Fulcio to include a mention of a transparency log and certificate authority respectively.

**Comment by haydentherapper** [comment]
Depending on the shades of red and blue, these colors are frequently related to US politics.

**Comment by tracymiranda** [comment]
Worth adding we've requested some options for rekor and new logo for gitsign so far, can also ask for other options for the other subprojects.

**Comment by SantiagoTorres** [comment]
>  Worth adding we've requested some options for rekor and new logo for gitsign so far, can also ask for other options for the other subprojects.

Perhaps rekor monitoring?

**Comment by tracymiranda** [comment]
Updated palettes and some new logo concepts for fulcio, with some notes from designer:

Palette: I've worked in that that lighter blue, and I completely understand about the blue on red! In setting up the colour palette options, I was verifying everything through a colour contrast checker to make sure that we have plenty of combinations that pass the contrast requirements for accessibility and the blue/red combination does pass for larger text but it’s not a combination that we need to use by any means, or might pull out occasionally if something calls for a funkier effect for decorative purposes where legibility isn’t a concern 😊 

Of course some of the project logos will be changing, but I’ve used them as examples of the coloured project logos anyway just to give an idea of different ways we can use the colours across a series of logos.

I don’t recommend we make ’Sigstore’ match the length of the project name because each project’s name is a different length. That means that the size of ’Sigstore’ would change from project to project, and in places where the project logos are displayed together, it starts to look wonky and inconsistent. In case it’s just a size concern though, I’ve included a version where the Sigstore name is larger but still consistently sized for consideration 😊
[Sigstore_Subprojects+Palette (1).pdf](https://github.com/sigstore/community/files/8952746/Sigstore_Subprojects%2BPalette.1.pdf)
[Sigstore_Fulcio_LogoConcepts (1).pdf](https://github.com/sigstore/community/files/8952747/Sigstore_Fulcio_LogoConcepts.1.pdf)

**Comment by haydentherapper** [comment]
For Fulcio:

Concept 1: Reminds me of the @ sign, evocative of email. I don't think that's a good fit for a CA, since code signing certs can include a number of identities besides email.

Concept 2: This logo is very similar to the GCP Certificate Authority Service [logo](https://www.keyfactor.com/wp-content/uploads/MicrosoftTeams-image-25.png), the one in blue that also uses a ribbon.

Concept 3: I like the shield motif, but I would prefer just the shield rather than two shields intertwined.

Maybe continuing to iterate on security-like objects in a shield?

**Comment by tracymiranda** [comment]
More input via sigstore slack thread: https://sigstore.slack.com/archives/C01DGF0G8U9/p1655845396863019

**Comment by jchestershopify** [comment]
The palette guidance on whether a colour can be used in regular or large type is very helpful.

**Comment by tracymiranda** [comment]
Updated full set of logos with suggested subproject colours on the same page as the main Sigstore colours for reference. 
[Sigstore_Subprojects_V4.pdf](https://github.com/sigstore/community/files/9041636/Sigstore_Subprojects_V4.pdf)

To be reviewed at community call on July 5th. Feedback welcome on this issue too.

**Comment by tracymiranda** [comment]
Feedback from community call: swap gitsign logo to green and avoid using red logos.

**Comment by tracymiranda** [comment]
The gitsign logo will be swapped to green. @lukehinds @bobcallaway @dlorenc please let me know any other feedback before we finalize the palettes & logos. 

![Screen Shot 2022-07-06 at 12 23 52 PM](https://user-images.githubusercontent.com/5173122/177598275-f6ca0682-d3d4-4e42-ba3f-47b0d803d8b2.png)

**Comment by tracymiranda** [comment]
Updated versions:
[Sigstore_Subprojects_V5.pdf](https://github.com/sigstore/community/files/9094757/Sigstore_Subprojects_V5.pdf)
<img width="750" alt="Screen Shot 2022-07-12 at 11 55 03 AM" src="https://user-images.githubusercontent.com/5173122/178536811-a8e750ca-559e-4afa-a03f-b797d19d5505.png">

**Comment by dlorenc** [comment]
+1 from me.

**Comment by lukehinds** [comment]
+1

**Comment by bobcallaway** [comment]
+1, thanks!
