### ISSUE TITLE
Gitsign Logo

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/community#67]
This is a distinct issue to track progress towards a logo for the gitsign subproject, though is part of the general sigstore logo refresh stage 2, see #61.

Gitsign should have it's own logo that is distinct but also in keeping with the new Sigstore logo.

**Comment by tracymiranda** [comment]
Logo concepts:
[Sigstore_Gitsign.pdf](https://github.com/sigstore/community/files/8995239/Sigstore_Gitsign.pdf)

**Comment by tracymiranda** [comment]
To simplify viewing and referencing designs have summarized them here:
![Screen Shot 2022-06-27 at 4 15 55 PM](https://user-images.githubusercontent.com/5173122/176028051-7e6f40ad-39bc-4122-9f55-42de4a36c357.png)

**Comment by omkensey** [comment]
I like 4 and 6 with the callback to the checkmark of signoff approval or the shield of protection that signatures provide.

**Comment by kaniini** [comment]
4 is good.  6 and 7 are bad because they don’t reflect the acyclic directed graph nature of Git.

**Comment by medberry** [comment]
5

**Comment by bradmccoydev** [comment]
1

**Comment by erikaheidi** [comment]
at first i liked 6 but what @kaniini said, it really doesn't represent git so well. so I'd go with **4**

**Comment by n3wscott** [comment]
4!

**Comment by pdxjohnny** [comment]
4

**Comment by tracymiranda** [comment]
Thanks all!
Additional feedback via slack: https://sigstore.slack.com/archives/C01DGF0G8U9/p1656361103075449
and twitter: 
https://twitter.com/tracymiranda/status/1541878290138468360?s=20&t=xNO6nnM6M2r4GbHh27Y3Kg
https://twitter.com/sabre1041/status/1541878754795986949?s=20&t=xNO6nnM6M2r4GbHh27Y3Kg

**Comment by tracymiranda** [comment]
On reviewing all the input the consensus was clear for logo 4 with its callback to the checkmark/signoff approval plus reflecting the acyclic directed graph nature of Git 😀. 
Final colour scheme to be settled as part of #61
